### ISSUE TITLE
package dependencies

### ISSUE THREAD

**Issue by mkleinsa** [umich-biostatistics/adaptBayes#18]
In the vignette, we load the packages:
library(mice);library(Hmisc);library(MASS);
library(rstan);library(Matrix);library(mnormt);
library(tidyverse);

If these packages are internally required for adaptBayes to work, the dependencies should be added to the DESCRIPTION file.

**Comment by psboonstra** [comment]
Hrmm..good point.

Definitely mice and rstan are dependencies.

Is there a way to methodically determine which others are internally 
required by adaptBayes? The challenge is that I *think* but am not 
certain that the remaining packages are only required for the vignette / 
simulations study, which to me would not make them dependencies.

**Comment by psboonstra** [comment]
fixed
